// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>


#nullable disable

namespace MTGView.Data.EFCore.Contexts.Configurations
{
    public partial class CardConfiguration : IEntityTypeConfiguration<MagicCard>
    {
        public void Configure(EntityTypeBuilder<MagicCard> entity)
        {
            entity.ToTable("Cards", "MTG");

            entity.HasIndex(e => e.setCode, "IX_Cards_SetCode")
                .IncludeProperties(e => new { e.colorIdentity, e.scryfallId, e.manaCost });
                
            entity.Property(e => e.id).ValueGeneratedNever();

            entity.Property(e => e.artist)
                .HasMaxLength(390)
                .IsUnicode(false);

            entity.Property(e => e.asciiName)
                .HasMaxLength(220)
                .IsUnicode(false);

            entity.Property(e => e.availability)
                .HasMaxLength(170)
                .IsUnicode(false);

            entity.Property(e => e.borderColor)
                .HasMaxLength(110)
                .IsUnicode(false);

            entity.Property(e => e.cardParts)
                .HasMaxLength(840)
                .IsUnicode(false);

            entity.Property(e => e.colorIdentity)
                .HasMaxLength(90)
                .IsUnicode(false);

            entity.Property(e => e.colorIndicator).HasMaxLength(450);

            entity.Property(e => e.colors)
                .HasMaxLength(90)
                .IsUnicode(false);

            entity.Property(e => e.duelDeck)
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.Property(e => e.faceFlavorName).IsUnicode(false);

            entity.Property(e => e.finishes)
                .HasMaxLength(130)
                .IsUnicode(false);

            entity.Property(e => e.flavorText)
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.frameEffects)
                .HasMaxLength(390)
                .IsUnicode(false);

            entity.Property(e => e.frameVersion)
                .HasMaxLength(600)
                .IsUnicode(false);

            entity.Property(e => e.keywords)
                .HasMaxLength(590)
                .IsUnicode(false);

            entity.Property(e => e.layout)
                .HasMaxLength(90)
                .IsUnicode(false);

            entity.Property(e => e.loyalty)
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.Property(e => e.manaCost)
                .HasMaxLength(330)
                .IsUnicode(false);

            entity.Property(e => e.manaValue)
                .HasColumnType("decimal(9,2)");

            entity.Property(e => e.mtgjsonV4Id)
                .HasMaxLength(390)
                .IsUnicode(false);

            entity.Property(e => e.name)
                .HasMaxLength(620)
                .IsUnicode(false);

            entity.Property(e => e.number)
                .HasMaxLength(60)
                .IsUnicode(false);

            entity.Property(e => e.originalPrintings)
                .HasMaxLength(800)
                .IsUnicode(false);

            entity.Property(e => e.originalReleaseDate).IsUnicode(false);

            entity.Property(e => e.otherFaceIds)
                .HasMaxLength(800)
                .IsUnicode(false);

            entity.Property(e => e.power)
                .HasMaxLength(12)
                .IsUnicode(false);

            entity.Property(e => e.printings)
                .HasMaxLength(1700)
                .IsUnicode(false);

            entity.Property(e => e.promoTypes)
                .HasMaxLength(220)
                .IsUnicode(false);

            entity.Property(e => e.purchaseUrls)
                .HasMaxLength(2760)
                .IsUnicode(false);

            entity.Property(e => e.rarity)
                .HasMaxLength(80)
                .IsUnicode(false);

            entity.Property(e => e.rebalancedPrintings)
                .HasMaxLength(390)
                .IsUnicode(false);

            entity.Property(e => e.securityStamp)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.setCode)
                .HasMaxLength(40)
                .IsUnicode(false);

            entity.Property(e => e.side)
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.Property(e => e.signature).IsUnicode(false);

            entity.Property(e => e.subtypes)
                .HasMaxLength(310)
                .IsUnicode(false);

            entity.Property(e => e.supertypes)
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.Property(e => e.text)
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.toughness)
                .HasMaxLength(12)
                .IsUnicode(false);

            entity.Property(e => e.type)
                .HasMaxLength(560)
                .IsUnicode(false);

            entity.Property(e => e.types)
                .HasMaxLength(220)
                .IsUnicode(false);

            entity.Property(e => e.watermark)
                .HasMaxLength(130)
                .IsUnicode(false);

            entity.Property(e => e.CollectionCardMappingId)
                .IsRequired(false);

            entity.HasIndex(e => e.CollectionCardMappingId)
                .HasDatabaseName("IX_Cards_CollectionCardMapping_Id")
                .IncludeProperties(e => new
                {
                    e.name,
                    e.manaCost,
                    e.setCode
                });

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<MagicCard> entity);
    }
}
