// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace MTGView.Data.EFCore.Contexts.Configurations
{
    public partial class LegalityConfiguration : IEntityTypeConfiguration<Legality>
    {
        public void Configure(EntityTypeBuilder<Legality> entity)
        {
            entity.ToTable("legalities", "MTG");

            entity.HasIndex(e => e.uuid, "IX_Legalities_Uuid");

            entity.HasIndex(e => e.status, "IX_Legalities_status");

            entity.Property(e => e.id).ValueGeneratedNever();

            entity.Property(e => e.format).HasMaxLength(50);

            entity.Property(e => e.status).HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Legality> entity);
    }
}
