// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace MTGView.Data.EFCore.Contexts.Configurations
{
    public partial class MetaConfiguration : IEntityTypeConfiguration<Meta>
    {
        public void Configure(EntityTypeBuilder<Meta> entity)
        {
            entity.ToTable("Meta", "MTG");

            entity.Property(e => e.id).ValueGeneratedNever();

            entity.Property(e => e.date).HasColumnType("date");

            entity.Property(e => e.version).HasMaxLength(100);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Meta> entity);
    }
}
