// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace MTGView.Data.EfCore.Contexts.Configurations;

internal partial class PersonalCardsConfiguration : IEntityTypeConfiguration<PersonalCard>
{
    public void Configure(EntityTypeBuilder<PersonalCard> entity)
    {
        entity.ToTable("Cards", "Personal");

        entity.HasKey(e => e.Id)
            .IsClustered();

        entity.Property(e => e.Id)
            .HasColumnName("id")
            .ValueGeneratedNever();

        entity.Property(e => e.Name)
            .HasColumnName("name")
            .HasMaxLength(620)
            .IsUnicode(false);

        entity.Property(e => e.SetCode)
            .HasColumnName("setCode")
            .HasMaxLength(40)
            .IsUnicode(false);

        entity.HasIndex(e => e.SetCode)
            .HasDatabaseName("IX_Cards_SetCode");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<PersonalCard> entity);
}