// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable disable

namespace MTGView.Data.EFCore.Contexts.Configurations
{
    public partial class SetConfiguration : IEntityTypeConfiguration<MagicSet>
    {
        public void Configure(EntityTypeBuilder<MagicSet> entity)
        {
            entity.ToTable("sets", "MTG");

            entity.HasIndex(e => e.code, "IX_Mtg_Sets_Code");

            entity.HasIndex(e => e.type, "IX_Mtg_Sets_Type");

            entity.Property(e => e.id).ValueGeneratedNever();

            entity.Property(e => e.block).HasMaxLength(50);

            entity.Property(e => e.code).HasMaxLength(50);

            entity.Property(e => e.keyruneCode).HasMaxLength(50);

            entity.Property(e => e.mcmIdExtras).HasColumnType("decimal(5, 1)");

            entity.Property(e => e.mcmName).HasMaxLength(50);

            entity.Property(e => e.mtgoCode).HasMaxLength(50);

            entity.Property(e => e.name).HasMaxLength(50);

            entity.Property(e => e.parentCode).HasMaxLength(50);

            entity.Property(e => e.sealedProduct).HasMaxLength(10);

            entity.Property(e => e.type).HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<MagicSet> entity);
    }
}
