// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace MTGView.Data.Personal.EfCore.Contexts;
public partial class PersonalcollectionsDbContext : DbContext
{
    public PersonalcollectionsDbContext(DbContextOptions<PersonalcollectionsDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<PersonalCard> Cards { get; set; } = null!;
    public virtual DbSet<PersonalCollection> Collections { get; set; } = null!;
    public virtual DbSet<PersonalCardMapping> Mappings { get; set; } = null!;

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.CardsConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CollectionsConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.MappingsConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
