// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
namespace MTGView.Core.Models;

public partial class Legality
{
    public int index { get; set; }
    public int id { get; set; }
    public string? format { get; set; }
    public string? status { get; set; }
    public Guid? uuid { get; set; }
}
