// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
#nullable enable

namespace MTGView.Core.Models;

public partial class MagicSet
{
    public int index { get; set; }
    public int id { get; set; }
    public int baseSetSize { get; set; }
    public string? block { get; set; }
    public string? booster { get; set; }
    public string code { get; set; } = null!;
    public bool isFoilOnly { get; set; }
    public bool isForeignOnly { get; set; }
    public bool isNonFoilOnly { get; set; }
    public bool isOnlineOnly { get; set; }
    public bool isPartialPreview { get; set; }
    public string keyruneCode { get; set; } = null!;
    public double? mcmId { get; set; }
    public decimal? mcmIdExtras { get; set; }
    public string? mcmName { get; set; }
    public string? mtgoCode { get; set; }
    public string name { get; set; } = null!;
    public string? parentCode { get; set; }
    public DateTime releaseDate { get; set; }
    public string? sealedProduct { get; set; }
    public double? tcgplayerGroupId { get; set; }
    public int totalSetSize { get; set; }
    public string type { get; set; } = null!;

    [NotMapped]
    [JsonPropertyName("cards")]
    public IEnumerable<MtgCardExcelData> Cards { get; set; }
}