// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace MTGView.Core.Models;
public partial class Meta
    {
        public int index { get; set; }
        public int id { get; set; }
        public DateTime date { get; set; }
        public string version { get; set; } = null!;
    }
