namespace MTGView.Core.Models;

public class MtgCardExcelData
{
    public int? index { get; set; }
    public int id { get; set; }
    public string? artist { get; set; }
    public string? asciiName { get; set; }
    public string? availability { get; set; }
    public string? borderColor { get; set; }
    public string? cardParts { get; set; }
    public string? colorIdentity { get; set; }
    public string? colorIndicator { get; set; }
    public string? colors { get; set; }
    public string? duelDeck { get; set; }
    public short? edhrecRank { get; set; }
    public string? faceFlavorName { get; set; }
    public string? finishes { get; set; }
    public string? flavorText { get; set; }
    public string? frameEffects { get; set; }
    public string? frameVersion { get; set; }
    public short? hasAlternativeDeckLimit { get; set; }
    public short? hasContentWarning { get; set; }
    public short? isAlternative { get; set; }
    public short? isFullArt { get; set; }
    public short? isFunny { get; set; }
    public short? isOnlineOnly { get; set; }
    public short? isOversized { get; set; }
    public short? isPromo { get; set; }
    public short? isRebalanced { get; set; }
    public short? isReprint { get; set; }
    public short? isReserved { get; set; }
    public short? isStarter { get; set; }
    public short? isStorySpotlight { get; set; }
    public short? isTextless { get; set; }
    public short? isTimeshifted { get; set; }
    public string? keywords { get; set; }
    public string? layout { get; set; }
    public short? life { get; set; }
    public string? loyalty { get; set; }
    public string? manaCost { get; set; }
    public short? manaValue { get; set; }
    public string? mtgjsonV4Id { get; set; }
    public int? mtgoFoilId { get; set; }
    public int? mtgoId { get; set; }
    public int? multiverseId { get; set; }
    public string? name { get; set; }
    public string? number { get; set; }
    public string? originalPrintings { get; set; }
    public string? originalReleaseDate { get; set; }
    public string? otherFaceIds { get; set; }
    public string? power { get; set; }
    public string? printings { get; set; }
    public string? promoTypes { get; set; }
    public string? purchaseUrls { get; set; }
    public string? rarity { get; set; }
    public string? rebalancedPrintings { get; set; }
    public Guid scryfallId { get; set; }
    public Guid? scryfallIllustrationId { get; set; }
    public Guid? scryfallOracleId { get; set; }
    public string? securityStamp { get; set; }
    public string? setCode { get; set; }
    public string? side { get; set; }
    public string? signature { get; set; }
    public string? subtypes { get; set; }
    public string? supertypes { get; set; }
    public string? text { get; set; }
    public string? toughness { get; set; }
    public string? type { get; set; }
    public string? types { get; set; }
    public Guid? uuid { get; set; }
    public string? variations { get; set; }
    public string? watermark { get; set; }
}