// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable
namespace MTGView.Core.Models;

public partial class Ruling
{
    [Column("index")]
    public int Index { get; set; }
    
    [Column("id")]
    public int Id { get; set; }

    [Column("date")]
    public DateTime CreatedAt { get; set; }

    [Column("text")]
    public string? RuleText { get; set; }
    
    [Column("uuid")]
    public Guid? RulingGuid { get; set; }
}
