// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace MTGView.Data.Personal.EfCore.Contexts.Configurations;

public partial class CollectionsConfiguration : IEntityTypeConfiguration<PersonalCollection>
{
    public void Configure(EntityTypeBuilder<PersonalCollection> entity)
    {
        entity.ToTable("Collections", "Personal");

        entity.HasKey(e => e.Id)
            .IsClustered();

        entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

        entity.Property(e => e.CreatedAt)
            .HasDefaultValueSql("getdate()")
            .HasPrecision(7);

        entity.Property(e => e.Name)
            .HasMaxLength(200)
            .IsRequired(false);

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<PersonalCollection> entity);
}