// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;

#nullable disable

namespace MTGView.Data.Personal.EfCore.Contexts.Configurations;

public partial class MappingsConfiguration : IEntityTypeConfiguration<PersonalCardMapping>
{
    public void Configure(EntityTypeBuilder<PersonalCardMapping> entity)
    {
        entity.ToTable("Mappings", "Personal");

        entity.HasKey(e => e.Id)
            .IsClustered();

        entity.HasIndex(e => e.CardId, "IX_PersonalCardMapping_CardId");

        entity.HasIndex(e => e.PersonalCollectionId, "IX_PersonalCardMapping_PersonalCollectionId");

        entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

        entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

        entity.HasOne(e => e.Collection)
            .WithMany(c => c.CardMappings)
            .HasForeignKey(e => e.PersonalCollectionId)
            .HasConstraintName("FK_Mappings_Collection_Id")
            .OnDelete(DeleteBehavior.ClientSetNull);

        entity.HasOne(e => e.Card)
            .WithMany(c => c.CardMappings)
            .HasForeignKey(e => e.CardId)
            .HasConstraintName("FK_Mappings_Card_Id")
            .OnDelete(DeleteBehavior.ClientSetNull);

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<PersonalCardMapping> entity);
}